### ISSUE TITLE
Using pre-trained weights ?

### ISSUE THREAD

**Issue by Dr-Champ** [arabian9ts/SSD300#15]
Hi,

Thanks for the new implementation of SSD for TF. The code looks organised, easy to read and very clean. However I'm not certain if we want to use pre-trained weights for the base model, say, from this [repo](https://github.com/tensorflow/tensorflow/tree/master/tensorflow/contrib/slim), how might we go about it? The code structure seems to imply I need to retrain all layers from scratch since it's not compatible with existing pre-trained models, am I correct?

Thanks

**Comment by arabian9ts** [comment]
@Dr-Champ Thanks for your comment.
I will use this repo for my study which requires trained for block-diagram detection.
However, there is not that parameters, so I'm not considering the compatibility.

I would like to fix this Non-compatibility someday.

Thanks.

**Comment by Dr-Champ** [comment]
Understood. I'll close this then. Thx !
